### Lista de Livros
GET http://localhost:5231/api/livros

### Cadastrar Livros
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "titulo" : "livro",
    "autor" : "clarice",
    "categoriaId" : 1 
}

### Deletar Livros
DELETE http://localhost:5231/api/livros/1

### Alterar Livros
PUT http://localhost:5231/api/livros/1
Content-Type: application/json

{
    "titulo" : "livro",
    "autor" : "clarice",
    "categoriaId" : 1
}