### Lista de Tarefas
GET http://localhost:5231/livros

### Cadastrar Tarefa
POST http://localhost:5231/livros
Content-Type: application/json

{
    "titulo" : "livro",
    "autor" : "clarice",
    "categoriaId" : 1
}

DELETE http://localhost:5231/livros/1

PUT http://localhost:5231/livros/1
Content-Type: application/json

{
    "titulo" : "livro",
    "autor" : "clarice",
    "categoriaId" : 1
}